DROP SCHEMA IF EXISTS john;

CREATE SCHEMA john;
USE john;

/* Table: user (Application Users) */
CREATE TABLE user (
    user_id     NVARCHAR(20) NOT NULL,
    password    NVARCHAR(20) NOT NULL,
    first_name  NVARCHAR(50) ,
    last_name   NVARCHAR(50) ,
    email       NVARCHAR(70) ,
    security_provider_id INT ,
    default_customer_id  INT ,
    company     NVARCHAR(50) ,
    phone       NVARCHAR(20) ,
    address1    NVARCHAR(100),
    address2    NVARCHAR(100),
    country     NVARCHAR(20) ,
    postal      NVARCHAR(20) ,
    role        NVARCHAR(20) ,
    other_roles NVARCHAR(80) ,
    is_active   BOOLEAN  ,
    is_blocked  BOOLEAN  ,
    secret_question     NVARCHAR(100),
    secret_answer       NVARCHAR(100),
    enable_beta_testing BOOLEAN,
    enable_renewal      BOOLEAN,
    CONSTRAINT user_id PRIMARY KEY(user_id)
);

create table robots(
serial_number    VARCHAR(32) NOT NULL ,
model    VARCHAR(32) NOT NULL ,
manufactured_date  TIMESTAMP NOT NULL,
category        VARCHAR(50) NOT NULL ,
PRIMARY KEY (serial_number)
);

CREATE TABLE survivors (
id              INT  generated by default as identity,
name    VARCHAR(25) NOT NULL DEFAULT 'John Doe',
age    INT(3) NOT NULL DEFAULT 0,
gender   CHAR(6) NOT NULL DEFAULT 'Male',
last_location  VARCHAR(25) NULL DEFAULT '-17.829167,31.052222',
PRIMARY KEY (id)
);

CREATE TABLE survivor_details(
id              INT  generated by default as identity,
user_id INT not null default 1,
survivor_id INT not null ,
infected BOOL NOT NULL DEFAULT FALSE,
last_location  VARCHAR(25) NULL,
from_date      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
thru_date      DATETIME NULL,
PRIMARY KEY (id)
);
create table survivors_survivor_details(
Survivor_id INT NOT NULL,
survivorDetails_id INT NOT NULL
);

create table survivor_inventory(
id INT  generated by default as identity,
survivor_id INT NOT NULL,
category  VARCHAR(25) NOT NULL DEFAULT 'UNKNOWN',
quantity INT NOT NULL DEFAULT 1,
PRIMARY KEY (id)
);


